name: CI Checks
on: pull_request
jobs:
  ci:
    name: Run Build and check output is checked-in
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
      - name: Use Node.js
        uses: actions/setup-node@c2ac33f2c62f978d6c944d9648125a294e56dc0b # main
        with:
          node-version: 20.x
      - name: 'Build'
        run: |
          cd action
          npm install
          npm run build
      - name: Check no files have changes
        run: git diff --exit-code
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
      - name: Use Node.js
        uses: actions/setup-node@c2ac33f2c62f978d6c944d9648125a294e56dc0b # main
        with:
          node-version: 20.x
      - name: Install NPM Packages
        run: |
          cd action
          npm install
      - name: Run Unit Tests
        run: |
          cd action
          npm run test -- --coverage
        env:
          GITHUB_SSH_PRIVATE_KEY: ${{ secrets.TESTING_PRIVATE_KEY }}
          GITHUB_SELF_TEST_REPO: ${{ github.repository }}
          GITHUB_SELF_TEST_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Linting
        run: |
          cd action
          npm run lint
      - name: Submit to CodeCov
        uses: codecov/codecov-action@d42a336584211c4f940f39382853503887003197 # main
        with:
          file: ./action/coverage/lcov.info
          fail_ci_if_error: false
